version: '2'
services:
  am-api:
    # container_name: access-management-server // Commented out to let docker choose names while scaling containers
    build:
      dockerfile: Dockerfile
    image: access-management-server:latest
    ports:
      - "8081-8090:8080"
    networks:
      - am-api-network
networks:
  am-api-network:
    driver: bridge